### ISSUE TITLE
Component.from_yaml() looks for local repo's path relative to cwd instead

### ISSUE THREAD

**Issue by andyk** [agentos-project/agentos#206]
to reproduce
```
$ cd agentos
$ python
>>> from agentos.component import Component
>>> Component.from_yaml("environment", "./example_agents/acme_r2d2/agentos.yaml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andyk/Development/agentos/agentos/component.py", line 99, in from_yaml
    components = Component.parse_spec_file(component_spec_file)
  File "/home/andyk/Development/agentos/agentos/component.py", line 202, in parse_spec_file
    components = Component._parse_components(
  File "/home/andyk/Development/agentos/agentos/component.py", line 219, in _parse_components
    component = Component.from_repo(
  File "/home/andyk/Development/agentos/agentos/component.py", line 129, in from_repo
    assert full_path.is_file(), f"{full_path} does not exist"
AssertionError: /home/andyk/Development/agentos/agent.py does not exist
```
I believe the issue is at
https://github.com/agentos-project/agentos/blob/68f65a673b1693b851a78e91996b37effa2459e0/agentos/repo.py#L41-L42
...which is getting the path from the repo spec but not then making it relative to the location of the yaml file that the repo is defined in.

**Comment by andyk** [comment]
This was fixed.
